services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ThreeBRS\SyliusPaymentRestrictionPlugin\Model\ThreeBRSSyliusResolvePaymentMethodForOrder:
        arguments:
            $zoneMatcher: '@sylius.zone_matcher'

    # Payment Method resolver
    threebrs.sylius_payment_restriction_plugin.payment.resolver.payment_methods_resolver:
        class: ThreeBRS\SyliusPaymentRestrictionPlugin\Resolver\PaymentMethodsResolver
        decorates: 'sylius.payment_methods_resolver.channel_based'
        decoration_priority: 256
        arguments:
            $decorated: '@.inner' # pass the old service as an argument
            $paymentMethodRepository: '@sylius.repository.payment_method'
            $paymentOrderResolver: '@ThreeBRS\SyliusPaymentRestrictionPlugin\Model\ThreeBRSSyliusResolvePaymentMethodForOrder'
    # Form extension
    ThreeBRS\SyliusPaymentRestrictionPlugin\Form\Extension\RestrictionPaymentMethodExtension:
        tags:
            - extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
              name: form.type_extension
        arguments:
            $shippingMethodClass: '%sylius.model.shipping_method.class%'
